### ISSUE TITLE
percySnapshot is not defined

### ISSUE THREAD

**Issue by kellyselden** [percy/ember-percy#38] opened 2017-08-15 18:03 UTC
I started getting this issue on CI this morning. No percy related changes.

https://travis-ci.org/kellyselden/package-hint-historic-resolver/jobs/264821527#L2740

**Comment by timhaines** [comment] 2017-08-15 18:06
Hi @kellyselden.  Did you upgrade ember-exam or anything else in the testing pipeline?  We haven't made a change recently that would obviously lead to this.

**Comment by kellyselden** [comment] 2017-08-15 18:09
I haven't. What happened was, greenkeeper gave me a PR for ember-cli-content-security-policy bumping to 1.0.0. Tests pass. Merged, then the failure. I haven't added new code to the project in forever, so what most likely happened is the npm cache got invalidated, and some dep is causing this now.

**Comment by kellyselden** [comment] 2017-08-15 18:10
hmmm I have a hunch it is ember-cli-babel 6.8.0, which was just released...

**Comment by timhaines** [comment] 2017-08-15 18:47
@kellyselden Thanks Kelly, it'd be great to hear if that's the cause.  Otherwise, we're happy to help troubleshoot.

**Comment by kellyselden** [comment] 2017-08-15 18:51
Here't the issue https://github.com/babel/ember-cli-babel/issues/178

I'm pretty sure it's related.

**Comment by rwjblue** [comment] 2017-08-15 18:51
https://github.com/ember-cli/babel-plugin-ember-modules-api-polyfill/pull/19 is the root cause

**Comment by rwjblue** [comment] 2017-08-15 18:52
basically `import './helpers/percy-snapshot'` is being removed, making the test helper undefined 😢

**Comment by rwjblue** [comment] 2017-08-15 19:01
ember-cli-babel@6.8.1 has been published, which should fix this

**Comment by timhaines** [comment] 2017-08-15 19:40
Thanks @rwjblue.  @kellyselden, I'm closing this issue.  But please do feel welcome to re-open or resubmit if there's anything we can assist with.

**Closed by timhaines** 2017-08-15 19:40 UTC
